### ISSUE TITLE
Readme ??

### ISSUE THREAD

**Issue by akshaynaik404** [ShubhamPurandare/VI1.2#1]

**Comment by ShubhamPurandare** [comment]
Readme file is added ... please check out

**Comment by akshaynaik404** [comment]
What you have included in the README gives good explaination of what the system is, but what should also be included and more focused in the README.md will be how one should setup the above mentioned project locally.

You can refer this https://github.com/facebookincubator/create-react-app#quick-overview as a sample readme. We can close this issue when installation steps are added.

**Comment by ShubhamPurandare** [comment]
Yes . I have added the Installation steps now . Sorry for inconvenience.
